/**
 * Auto-generated endpoint tests from OpenAPI spec.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Run `npx tsx scripts/generate-endpoint-tests.ts` to regenerate.
 */

import { describe, it, expect } from 'vitest';
import Late from '../src';

describe('Endpoint Methods', () => {
  const client = new Late({ apiKey: "test_key" });

  describe('account Groups', () => {
    it('should have listAccountGroups method', () => {
      expect(client.accountGroups.listAccountGroups).toBeDefined();
      expect(client.accountGroups.listAccountGroups).toBeTypeOf('function');
    });

    it('should have createAccountGroup method', () => {
      expect(client.accountGroups.createAccountGroup).toBeDefined();
      expect(client.accountGroups.createAccountGroup).toBeTypeOf('function');
    });

    it('should have updateAccountGroup method', () => {
      expect(client.accountGroups.updateAccountGroup).toBeDefined();
      expect(client.accountGroups.updateAccountGroup).toBeTypeOf('function');
    });

    it('should have deleteAccountGroup method', () => {
      expect(client.accountGroups.deleteAccountGroup).toBeDefined();
      expect(client.accountGroups.deleteAccountGroup).toBeTypeOf('function');
    });

  });

  describe('accounts', () => {
    it('should have listAccounts method', () => {
      expect(client.accounts.listAccounts).toBeDefined();
      expect(client.accounts.listAccounts).toBeTypeOf('function');
    });

    it('should have getFollowerStats method', () => {
      expect(client.accounts.getFollowerStats).toBeDefined();
      expect(client.accounts.getFollowerStats).toBeTypeOf('function');
    });

    it('should have updateAccount method', () => {
      expect(client.accounts.updateAccount).toBeDefined();
      expect(client.accounts.updateAccount).toBeTypeOf('function');
    });

    it('should have deleteAccount method', () => {
      expect(client.accounts.deleteAccount).toBeDefined();
      expect(client.accounts.deleteAccount).toBeTypeOf('function');
    });

    it('should have getAllAccountsHealth method', () => {
      expect(client.accounts.getAllAccountsHealth).toBeDefined();
      expect(client.accounts.getAllAccountsHealth).toBeTypeOf('function');
    });

    it('should have getAccountHealth method', () => {
      expect(client.accounts.getAccountHealth).toBeDefined();
      expect(client.accounts.getAccountHealth).toBeTypeOf('function');
    });

    it('should have getTikTokCreatorInfo method', () => {
      expect(client.accounts.getTikTokCreatorInfo).toBeDefined();
      expect(client.accounts.getTikTokCreatorInfo).toBeTypeOf('function');
    });

    it('should have getGoogleBusinessReviews method', () => {
      expect(client.accounts.getGoogleBusinessReviews).toBeDefined();
      expect(client.accounts.getGoogleBusinessReviews).toBeTypeOf('function');
    });

    it('should have getLinkedInMentions method', () => {
      expect(client.accounts.getLinkedInMentions).toBeDefined();
      expect(client.accounts.getLinkedInMentions).toBeTypeOf('function');
    });

  });

  describe('analytics', () => {
    it('should have getAnalytics method', () => {
      expect(client.analytics.getAnalytics).toBeDefined();
      expect(client.analytics.getAnalytics).toBeTypeOf('function');
    });

    it('should have getYouTubeDailyViews method', () => {
      expect(client.analytics.getYouTubeDailyViews).toBeDefined();
      expect(client.analytics.getYouTubeDailyViews).toBeTypeOf('function');
    });

    it('should have getInstagramAccountInsights method', () => {
      expect(client.analytics.getInstagramAccountInsights).toBeDefined();
      expect(client.analytics.getInstagramAccountInsights).toBeTypeOf('function');
    });

    it('should have getInstagramDemographics method', () => {
      expect(client.analytics.getInstagramDemographics).toBeDefined();
      expect(client.analytics.getInstagramDemographics).toBeTypeOf('function');
    });

    it('should have getDailyMetrics method', () => {
      expect(client.analytics.getDailyMetrics).toBeDefined();
      expect(client.analytics.getDailyMetrics).toBeTypeOf('function');
    });

    it('should have getBestTimeToPost method', () => {
      expect(client.analytics.getBestTimeToPost).toBeDefined();
      expect(client.analytics.getBestTimeToPost).toBeTypeOf('function');
    });

    it('should have getContentDecay method', () => {
      expect(client.analytics.getContentDecay).toBeDefined();
      expect(client.analytics.getContentDecay).toBeTypeOf('function');
    });

    it('should have getPostingFrequency method', () => {
      expect(client.analytics.getPostingFrequency).toBeDefined();
      expect(client.analytics.getPostingFrequency).toBeTypeOf('function');
    });

    it('should have getPostTimeline method', () => {
      expect(client.analytics.getPostTimeline).toBeDefined();
      expect(client.analytics.getPostTimeline).toBeTypeOf('function');
    });

    it('should have getLinkedInAggregateAnalytics method', () => {
      expect(client.analytics.getLinkedInAggregateAnalytics).toBeDefined();
      expect(client.analytics.getLinkedInAggregateAnalytics).toBeTypeOf('function');
    });

    it('should have getLinkedInPostAnalytics method', () => {
      expect(client.analytics.getLinkedInPostAnalytics).toBeDefined();
      expect(client.analytics.getLinkedInPostAnalytics).toBeTypeOf('function');
    });

    it('should have getLinkedInPostReactions method', () => {
      expect(client.analytics.getLinkedInPostReactions).toBeDefined();
      expect(client.analytics.getLinkedInPostReactions).toBeTypeOf('function');
    });

  });

  describe('api Keys', () => {
    it('should have listApiKeys method', () => {
      expect(client.apiKeys.listApiKeys).toBeDefined();
      expect(client.apiKeys.listApiKeys).toBeTypeOf('function');
    });

    it('should have createApiKey method', () => {
      expect(client.apiKeys.createApiKey).toBeDefined();
      expect(client.apiKeys.createApiKey).toBeTypeOf('function');
    });

    it('should have deleteApiKey method', () => {
      expect(client.apiKeys.deleteApiKey).toBeDefined();
      expect(client.apiKeys.deleteApiKey).toBeTypeOf('function');
    });

  });

  describe('connect', () => {
    it('should have getConnectUrl method', () => {
      expect(client.connect.getConnectUrl).toBeDefined();
      expect(client.connect.getConnectUrl).toBeTypeOf('function');
    });

    it('should have handleOAuthCallback method', () => {
      expect(client.connect.handleOAuthCallback).toBeDefined();
      expect(client.connect.handleOAuthCallback).toBeTypeOf('function');
    });

    it('should have getPendingOAuthData method', () => {
      expect(client.connect.getPendingOAuthData).toBeDefined();
      expect(client.connect.getPendingOAuthData).toBeTypeOf('function');
    });

    it('should have connectWhatsAppCredentials method', () => {
      expect(client.connect.connectWhatsAppCredentials).toBeDefined();
      expect(client.connect.connectWhatsAppCredentials).toBeTypeOf('function');
    });

    it('should have getFacebookPages method', () => {
      expect(client.connect.getFacebookPages).toBeDefined();
      expect(client.connect.getFacebookPages).toBeTypeOf('function');
    });

    it('should have updateFacebookPage method', () => {
      expect(client.connect.updateFacebookPage).toBeDefined();
      expect(client.connect.updateFacebookPage).toBeTypeOf('function');
    });

    it('should have getLinkedInOrganizations method', () => {
      expect(client.connect.getLinkedInOrganizations).toBeDefined();
      expect(client.connect.getLinkedInOrganizations).toBeTypeOf('function');
    });

    it('should have updateLinkedInOrganization method', () => {
      expect(client.connect.updateLinkedInOrganization).toBeDefined();
      expect(client.connect.updateLinkedInOrganization).toBeTypeOf('function');
    });

    it('should have getPinterestBoards method', () => {
      expect(client.connect.getPinterestBoards).toBeDefined();
      expect(client.connect.getPinterestBoards).toBeTypeOf('function');
    });

    it('should have updatePinterestBoards method', () => {
      expect(client.connect.updatePinterestBoards).toBeDefined();
      expect(client.connect.updatePinterestBoards).toBeTypeOf('function');
    });

    it('should have getGmbLocations method', () => {
      expect(client.connect.getGmbLocations).toBeDefined();
      expect(client.connect.getGmbLocations).toBeTypeOf('function');
    });

    it('should have updateGmbLocation method', () => {
      expect(client.connect.updateGmbLocation).toBeDefined();
      expect(client.connect.updateGmbLocation).toBeTypeOf('function');
    });

    it('should have getRedditSubreddits method', () => {
      expect(client.connect.getRedditSubreddits).toBeDefined();
      expect(client.connect.getRedditSubreddits).toBeTypeOf('function');
    });

    it('should have updateRedditSubreddits method', () => {
      expect(client.connect.updateRedditSubreddits).toBeDefined();
      expect(client.connect.updateRedditSubreddits).toBeTypeOf('function');
    });

    it('should have getRedditFlairs method', () => {
      expect(client.connect.getRedditFlairs).toBeDefined();
      expect(client.connect.getRedditFlairs).toBeTypeOf('function');
    });

  });

  describe('connect.bluesky', () => {
    it('should have connectBlueskyCredentials method', () => {
      expect(client.connect.bluesky.connectBlueskyCredentials).toBeDefined();
      expect(client.connect.bluesky.connectBlueskyCredentials).toBeTypeOf('function');
    });

  });

  describe('connect.facebook', () => {
    it('should have listFacebookPages method', () => {
      expect(client.connect.facebook.listFacebookPages).toBeDefined();
      expect(client.connect.facebook.listFacebookPages).toBeTypeOf('function');
    });

    it('should have selectFacebookPage method', () => {
      expect(client.connect.facebook.selectFacebookPage).toBeDefined();
      expect(client.connect.facebook.selectFacebookPage).toBeTypeOf('function');
    });

  });

  describe('connect.google Business', () => {
    it('should have listGoogleBusinessLocations method', () => {
      expect(client.connect.googleBusiness.listGoogleBusinessLocations).toBeDefined();
      expect(client.connect.googleBusiness.listGoogleBusinessLocations).toBeTypeOf('function');
    });

    it('should have selectGoogleBusinessLocation method', () => {
      expect(client.connect.googleBusiness.selectGoogleBusinessLocation).toBeDefined();
      expect(client.connect.googleBusiness.selectGoogleBusinessLocation).toBeTypeOf('function');
    });

  });

  describe('connect.linkedin', () => {
    it('should have listLinkedInOrganizations method', () => {
      expect(client.connect.linkedin.listLinkedInOrganizations).toBeDefined();
      expect(client.connect.linkedin.listLinkedInOrganizations).toBeTypeOf('function');
    });

    it('should have selectLinkedInOrganization method', () => {
      expect(client.connect.linkedin.selectLinkedInOrganization).toBeDefined();
      expect(client.connect.linkedin.selectLinkedInOrganization).toBeTypeOf('function');
    });

  });

  describe('connect.pinterest', () => {
    it('should have listPinterestBoardsForSelection method', () => {
      expect(client.connect.pinterest.listPinterestBoardsForSelection).toBeDefined();
      expect(client.connect.pinterest.listPinterestBoardsForSelection).toBeTypeOf('function');
    });

    it('should have selectPinterestBoard method', () => {
      expect(client.connect.pinterest.selectPinterestBoard).toBeDefined();
      expect(client.connect.pinterest.selectPinterestBoard).toBeTypeOf('function');
    });

  });

  describe('connect.snapchat', () => {
    it('should have listSnapchatProfiles method', () => {
      expect(client.connect.snapchat.listSnapchatProfiles).toBeDefined();
      expect(client.connect.snapchat.listSnapchatProfiles).toBeTypeOf('function');
    });

    it('should have selectSnapchatProfile method', () => {
      expect(client.connect.snapchat.selectSnapchatProfile).toBeDefined();
      expect(client.connect.snapchat.selectSnapchatProfile).toBeTypeOf('function');
    });

  });

  describe('connect.telegram', () => {
    it('should have getTelegramConnectStatus method', () => {
      expect(client.connect.telegram.getTelegramConnectStatus).toBeDefined();
      expect(client.connect.telegram.getTelegramConnectStatus).toBeTypeOf('function');
    });

    it('should have initiateTelegramConnect method', () => {
      expect(client.connect.telegram.initiateTelegramConnect).toBeDefined();
      expect(client.connect.telegram.initiateTelegramConnect).toBeTypeOf('function');
    });

    it('should have completeTelegramConnect method', () => {
      expect(client.connect.telegram.completeTelegramConnect).toBeDefined();
      expect(client.connect.telegram.completeTelegramConnect).toBeTypeOf('function');
    });

  });

  describe('invites', () => {
    it('should have createInviteToken method', () => {
      expect(client.invites.createInviteToken).toBeDefined();
      expect(client.invites.createInviteToken).toBeTypeOf('function');
    });

  });

  describe('logs', () => {
    it('should have listPostsLogs method', () => {
      expect(client.logs.listPostsLogs).toBeDefined();
      expect(client.logs.listPostsLogs).toBeTypeOf('function');
    });

    it('should have listConnectionLogs method', () => {
      expect(client.logs.listConnectionLogs).toBeDefined();
      expect(client.logs.listConnectionLogs).toBeTypeOf('function');
    });

    it('should have getPostLogs method', () => {
      expect(client.logs.getPostLogs).toBeDefined();
      expect(client.logs.getPostLogs).toBeTypeOf('function');
    });

  });

  describe('media', () => {
    it('should have getMediaPresignedUrl method', () => {
      expect(client.media.getMediaPresignedUrl).toBeDefined();
      expect(client.media.getMediaPresignedUrl).toBeTypeOf('function');
    });

  });

  describe('posts', () => {
    it('should have listPosts method', () => {
      expect(client.posts.listPosts).toBeDefined();
      expect(client.posts.listPosts).toBeTypeOf('function');
    });

    it('should have createPost method', () => {
      expect(client.posts.createPost).toBeDefined();
      expect(client.posts.createPost).toBeTypeOf('function');
    });

    it('should have getPost method', () => {
      expect(client.posts.getPost).toBeDefined();
      expect(client.posts.getPost).toBeTypeOf('function');
    });

    it('should have updatePost method', () => {
      expect(client.posts.updatePost).toBeDefined();
      expect(client.posts.updatePost).toBeTypeOf('function');
    });

    it('should have deletePost method', () => {
      expect(client.posts.deletePost).toBeDefined();
      expect(client.posts.deletePost).toBeTypeOf('function');
    });

    it('should have bulkUploadPosts method', () => {
      expect(client.posts.bulkUploadPosts).toBeDefined();
      expect(client.posts.bulkUploadPosts).toBeTypeOf('function');
    });

    it('should have retryPost method', () => {
      expect(client.posts.retryPost).toBeDefined();
      expect(client.posts.retryPost).toBeTypeOf('function');
    });

    it('should have unpublishPost method', () => {
      expect(client.posts.unpublishPost).toBeDefined();
      expect(client.posts.unpublishPost).toBeTypeOf('function');
    });

    it('should have updatePostMetadata method', () => {
      expect(client.posts.updatePostMetadata).toBeDefined();
      expect(client.posts.updatePostMetadata).toBeTypeOf('function');
    });

  });

  describe('profiles', () => {
    it('should have listProfiles method', () => {
      expect(client.profiles.listProfiles).toBeDefined();
      expect(client.profiles.listProfiles).toBeTypeOf('function');
    });

    it('should have createProfile method', () => {
      expect(client.profiles.createProfile).toBeDefined();
      expect(client.profiles.createProfile).toBeTypeOf('function');
    });

    it('should have getProfile method', () => {
      expect(client.profiles.getProfile).toBeDefined();
      expect(client.profiles.getProfile).toBeTypeOf('function');
    });

    it('should have updateProfile method', () => {
      expect(client.profiles.updateProfile).toBeDefined();
      expect(client.profiles.updateProfile).toBeTypeOf('function');
    });

    it('should have deleteProfile method', () => {
      expect(client.profiles.deleteProfile).toBeDefined();
      expect(client.profiles.deleteProfile).toBeTypeOf('function');
    });

  });

  describe('queue', () => {
    it('should have listQueueSlots method', () => {
      expect(client.queue.listQueueSlots).toBeDefined();
      expect(client.queue.listQueueSlots).toBeTypeOf('function');
    });

    it('should have createQueueSlot method', () => {
      expect(client.queue.createQueueSlot).toBeDefined();
      expect(client.queue.createQueueSlot).toBeTypeOf('function');
    });

    it('should have updateQueueSlot method', () => {
      expect(client.queue.updateQueueSlot).toBeDefined();
      expect(client.queue.updateQueueSlot).toBeTypeOf('function');
    });

    it('should have deleteQueueSlot method', () => {
      expect(client.queue.deleteQueueSlot).toBeDefined();
      expect(client.queue.deleteQueueSlot).toBeTypeOf('function');
    });

    it('should have previewQueue method', () => {
      expect(client.queue.previewQueue).toBeDefined();
      expect(client.queue.previewQueue).toBeTypeOf('function');
    });

    it('should have getNextQueueSlot method', () => {
      expect(client.queue.getNextQueueSlot).toBeDefined();
      expect(client.queue.getNextQueueSlot).toBeTypeOf('function');
    });

  });

  describe('reddit', () => {
    it('should have searchReddit method', () => {
      expect(client.reddit.searchReddit).toBeDefined();
      expect(client.reddit.searchReddit).toBeTypeOf('function');
    });

    it('should have getRedditFeed method', () => {
      expect(client.reddit.getRedditFeed).toBeDefined();
      expect(client.reddit.getRedditFeed).toBeTypeOf('function');
    });

  });

  describe('tools', () => {
    it('should have downloadYouTubeVideo method', () => {
      expect(client.tools.downloadYouTubeVideo).toBeDefined();
      expect(client.tools.downloadYouTubeVideo).toBeTypeOf('function');
    });

    it('should have getYouTubeTranscript method', () => {
      expect(client.tools.getYouTubeTranscript).toBeDefined();
      expect(client.tools.getYouTubeTranscript).toBeTypeOf('function');
    });

    it('should have downloadInstagramMedia method', () => {
      expect(client.tools.downloadInstagramMedia).toBeDefined();
      expect(client.tools.downloadInstagramMedia).toBeTypeOf('function');
    });

    it('should have checkInstagramHashtags method', () => {
      expect(client.tools.checkInstagramHashtags).toBeDefined();
      expect(client.tools.checkInstagramHashtags).toBeTypeOf('function');
    });

    it('should have downloadTikTokVideo method', () => {
      expect(client.tools.downloadTikTokVideo).toBeDefined();
      expect(client.tools.downloadTikTokVideo).toBeTypeOf('function');
    });

    it('should have downloadTwitterMedia method', () => {
      expect(client.tools.downloadTwitterMedia).toBeDefined();
      expect(client.tools.downloadTwitterMedia).toBeTypeOf('function');
    });

    it('should have downloadFacebookVideo method', () => {
      expect(client.tools.downloadFacebookVideo).toBeDefined();
      expect(client.tools.downloadFacebookVideo).toBeTypeOf('function');
    });

    it('should have downloadLinkedInVideo method', () => {
      expect(client.tools.downloadLinkedInVideo).toBeDefined();
      expect(client.tools.downloadLinkedInVideo).toBeTypeOf('function');
    });

    it('should have downloadBlueskyMedia method', () => {
      expect(client.tools.downloadBlueskyMedia).toBeDefined();
      expect(client.tools.downloadBlueskyMedia).toBeTypeOf('function');
    });

  });

  describe('usage', () => {
    it('should have getUsageStats method', () => {
      expect(client.usage.getUsageStats).toBeDefined();
      expect(client.usage.getUsageStats).toBeTypeOf('function');
    });

  });

  describe('users', () => {
    it('should have listUsers method', () => {
      expect(client.users.listUsers).toBeDefined();
      expect(client.users.listUsers).toBeTypeOf('function');
    });

    it('should have getUser method', () => {
      expect(client.users.getUser).toBeDefined();
      expect(client.users.getUser).toBeTypeOf('function');
    });

  });

  describe('webhooks', () => {
    it('should have getWebhookSettings method', () => {
      expect(client.webhooks.getWebhookSettings).toBeDefined();
      expect(client.webhooks.getWebhookSettings).toBeTypeOf('function');
    });

    it('should have createWebhookSettings method', () => {
      expect(client.webhooks.createWebhookSettings).toBeDefined();
      expect(client.webhooks.createWebhookSettings).toBeTypeOf('function');
    });

    it('should have updateWebhookSettings method', () => {
      expect(client.webhooks.updateWebhookSettings).toBeDefined();
      expect(client.webhooks.updateWebhookSettings).toBeTypeOf('function');
    });

    it('should have deleteWebhookSettings method', () => {
      expect(client.webhooks.deleteWebhookSettings).toBeDefined();
      expect(client.webhooks.deleteWebhookSettings).toBeTypeOf('function');
    });

    it('should have testWebhook method', () => {
      expect(client.webhooks.testWebhook).toBeDefined();
      expect(client.webhooks.testWebhook).toBeTypeOf('function');
    });

    it('should have getWebhookLogs method', () => {
      expect(client.webhooks.getWebhookLogs).toBeDefined();
      expect(client.webhooks.getWebhookLogs).toBeTypeOf('function');
    });

  });

});